version: 2.1
jobs:
  ubuntu2004_debian11:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: "Prepare image with systemd enabled"
          command: sudo docker build --tag debian_systemd - < Dockerfile_debian11_systemd
      - run: 
          name: "Deploy new systemd enabled image"
          command: sudo docker run -d -v /sys/fs/cgroup/:/sys/fs/cgroup:ro --privileged --cap-add SYS_ADMIN  --name linux_systemd_container debian_systemd /lib/systemd/systemd
      - run: sudo docker ps
      - run: sudo docker exec -it linux_systemd_container systemctl status --no-pager
      - run: sudo docker exec -it linux_systemd_container apt install -y wget
      - run: sudo docker exec -it linux_systemd_container wget https://install.fastnetmon.com/installer?veryrandomarg -Oinstaller
      - run: sudo docker exec -it linux_systemd_container chmod +x installer
      - run: sudo docker exec --env "CI=true" -it linux_systemd_container ./installer -do_not_check_license
      - run: sudo docker exec --env -it linux_systemd_container cat /var/log/fastnetmon/fastnetmon.log
      - run: sudo docker exec --env -it linux_systemd_container ldd /opt/fastnetmon/app/bin/fastnetmon
      - run: sudo docker exec --env -it linux_systemd_container ldd /opt/fastnetmon/app/bin/traffic_db
      - run: sudo docker exec --env -it linux_systemd_container ldd /opt/fastnetmon/app/bin/fill_dictionaries
      - run: sudo docker exec --env -it linux_systemd_container /opt/fastnetmon/app/bin/fastnetmon --configuration_check
      - run: sudo docker exec --env -it linux_systemd_container fcli show fastnetmon_version
      - run: sudo docker exec --env "CI=true" -it linux_systemd_container ./installer -install_graphic_stack
  ubuntu2004_debian10:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: "Prepare image with systemd enabled"
          command: sudo docker build --tag debian_systemd - < Dockerfile_debian10_systemd
      - run: 
          name: "Deploy new systemd enabled image"
          command: sudo docker run -d -v /sys/fs/cgroup/:/sys/fs/cgroup:ro --privileged --cap-add SYS_ADMIN  --name linux_systemd_container debian_systemd /lib/systemd/systemd
      - run: sudo docker ps
      - run: sudo docker exec -it linux_systemd_container systemctl status --no-pager
      - run: sudo docker exec -it linux_systemd_container apt install -y wget
      - run: sudo docker exec -it linux_systemd_container wget https://install.fastnetmon.com/installer?veryrandomarg -Oinstaller
      - run: sudo docker exec -it linux_systemd_container chmod +x installer
      - run: sudo docker exec --env "CI=true" -it linux_systemd_container ./installer -do_not_check_license
      - run: sudo docker exec --env -it linux_systemd_container cat /var/log/fastnetmon/fastnetmon.log
      - run: sudo docker exec --env -it linux_systemd_container ldd /opt/fastnetmon/app/bin/fastnetmon
      - run: sudo docker exec --env -it linux_systemd_container ldd /opt/fastnetmon/app/bin/traffic_db
      - run: sudo docker exec --env -it linux_systemd_container ldd /opt/fastnetmon/app/bin/fill_dictionaries
      - run: sudo docker exec --env -it linux_systemd_container /opt/fastnetmon/app/bin/fastnetmon --configuration_check
      - run: sudo docker exec --env -it linux_systemd_container fcli show fastnetmon_version
      - run: sudo docker exec --env "CI=true" -it linux_systemd_container ./installer -install_graphic_stack
  ubuntu2004_debian9:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: "Prepare image with systemd enabled"
          command: sudo docker build --tag debian_systemd - < Dockerfile_debian9_systemd
      - run: 
          name: "Deploy new systemd enabled image"
          command: sudo docker run -d -v /sys/fs/cgroup/:/sys/fs/cgroup:ro --privileged --cap-add SYS_ADMIN  --name linux_systemd_container debian_systemd /lib/systemd/systemd
      - run: sudo docker ps
      - run: sudo docker exec -it linux_systemd_container systemctl status --no-pager
      - run: sudo docker exec -it linux_systemd_container apt install -y wget
      - run: sudo docker exec -it linux_systemd_container wget https://install.fastnetmon.com/installer?veryrandomarg -Oinstaller
      - run: sudo docker exec -it linux_systemd_container chmod +x installer
      - run: sudo docker exec --env "CI=true" -it linux_systemd_container ./installer -do_not_check_license
      - run: sudo docker exec --env -it linux_systemd_container cat /var/log/fastnetmon/fastnetmon.log
      - run: sudo docker exec --env -it linux_systemd_container ldd /opt/fastnetmon/app/bin/fastnetmon
      - run: sudo docker exec --env -it linux_systemd_container ldd /opt/fastnetmon/app/bin/traffic_db
      - run: sudo docker exec --env -it linux_systemd_container ldd /opt/fastnetmon/app/bin/fill_dictionaries
      - run: sudo docker exec --env -it linux_systemd_container /opt/fastnetmon/app/bin/fastnetmon --configuration_check
      - run: sudo docker exec --env -it linux_systemd_container fcli show fastnetmon_version
      - run: sudo docker exec --env "CI=true" -it linux_systemd_container ./installer -install_graphic_stack
  ubuntu2004_centos7:
    machine:
      image: ubuntu-2004:current
    steps:
      - run: sudo docker run -d -v /sys/fs/cgroup/:/sys/fs/cgroup:ro --privileged --cap-add SYS_ADMIN  --name linux_systemd_container centos:centos7 /sbin/init
      - run: sudo docker ps
      - run: sudo docker exec -it linux_systemd_container systemctl status --no-pager
      - run: sudo docker exec -it linux_systemd_container yum install -y wget
      - run: sudo docker exec -it linux_systemd_container wget --no-check-certificate https://install.fastnetmon.com/installer?veryrandomarg -Oinstaller
      - run: sudo docker exec -it linux_systemd_container chmod +x installer
      - run: sudo docker exec --env "CI=true" -it linux_systemd_container ./installer -do_not_check_license
      - run: sudo docker exec --env -it linux_systemd_container cat /var/log/fastnetmon/fastnetmon.log
      - run: sudo docker exec --env -it linux_systemd_container ldd /opt/fastnetmon/app/bin/fastnetmon
      - run: sudo docker exec --env -it linux_systemd_container ldd /opt/fastnetmon/app/bin/traffic_db
      - run: sudo docker exec --env -it linux_systemd_container ldd /opt/fastnetmon/app/bin/fill_dictionaries
      - run: sudo docker exec --env -it linux_systemd_container /opt/fastnetmon/app/bin/fastnetmon --configuration_check
      - run: sudo docker exec --env -it linux_systemd_container fcli show fastnetmon_version
      - run: sudo docker exec --env "CI=true" -it linux_systemd_container ./installer -install_graphic_stack
  ubuntu2004_almalinux8:
    machine:
      image: ubuntu-2004:current
    steps:
      - run: sudo docker run -d -v /sys/fs/cgroup/:/sys/fs/cgroup:ro --privileged --cap-add SYS_ADMIN  --name linux_systemd_container almalinux:8 /sbin/init
      - run: sudo docker ps
      - run: sudo docker exec -it linux_systemd_container systemctl status --no-pager
      - run: sudo docker exec -it linux_systemd_container yum install -y wget
      - run: sudo docker exec -it linux_systemd_container wget https://install.fastnetmon.com/installer?veryrandomarg -Oinstaller
      - run: sudo docker exec -it linux_systemd_container chmod +x installer
      - run: sudo docker exec --env "CI=true" -it linux_systemd_container ./installer -do_not_check_license
      - run: sudo docker exec --env -it linux_systemd_container cat /var/log/fastnetmon/fastnetmon.log
      - run: sudo docker exec --env -it linux_systemd_container ldd /opt/fastnetmon/app/bin/fastnetmon
      - run: sudo docker exec --env -it linux_systemd_container ldd /opt/fastnetmon/app/bin/traffic_db
      - run: sudo docker exec --env -it linux_systemd_container ldd /opt/fastnetmon/app/bin/fill_dictionaries
      - run: sudo docker exec --env -it linux_systemd_container /opt/fastnetmon/app/bin/fastnetmon --configuration_check
      - run: sudo docker exec --env -it linux_systemd_container fcli show fastnetmon_version
      - run: sudo docker exec --env "CI=true" -it linux_systemd_container ./installer -install_graphic_stack
  ubuntu2004:
    machine:
      image: ubuntu-2004:current
    steps:
      - run: sudo apt-get update
      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -y wget systemd
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: sudo CI=true ./installer -do_not_check_license
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/app/bin/fastnetmon
      - run: ldd /opt/fastnetmon/app/bin/traffic_db
      - run: ldd /opt/fastnetmon/app/bin/fill_dictionaries
      - run: sudo /opt/fastnetmon/app/bin/fastnetmon --configuration_check
      - store_artifacts:
          path: /var/log/fastnetmon/fastnetmon.log
      - run: sudo fcli show fastnetmon_version
      - run: sudo CI=true ./installer -install_graphic_stack
  ubuntu2004_docker:
    machine:
      image: ubuntu-2004:current
    steps:
      - run: sudo apt-get update
      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: sudo CI=true ./installer -fastnetmon_docker
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: sudo chmod -R 755 /var/lib/fastnetmon_docker # make permissions more relaxed to get log file as artifact
      - store_artifacts:
          path: /var/lib/fastnetmon_docker/fastnetmon/logs/fastnetmon.log
      - run: sudo fcli show fastnetmon_version
workflows:
  version: 2
  all_distros_nightly:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - ubuntu2004
      - ubuntu2004_docker
      - ubuntu2004_centos7
      - ubuntu2004_almalinux8
      - ubuntu2004_debian9
      - ubuntu2004_debian10
      - ubuntu2004_debian11
  all_distros:
    jobs:
      - ubuntu2004
      - ubuntu2004_docker
      - ubuntu2004_centos7
      - ubuntu2004_almalinux8
      - ubuntu2004_debian9
      - ubuntu2004_debian10
      - ubuntu2004_debian11
