version: 2.1
jobs:
  ubuntu2004:
    machine:
      image: ubuntu-2004:current
    steps:
      - run: sudo apt-get update
      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -y wget systemd
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: sudo CI=true ./installer -do_not_check_license
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/app/bin/fastnetmon
      - run: ldd /opt/fastnetmon/app/bin/traffic_db
      - run: ldd /opt/fastnetmon/app/bin/fill_dictionaries
      - run: sudo /opt/fastnetmon/app/bin/fastnetmon --configuration_check
      - store_artifacts:
          path: /var/log/fastnetmon/fastnetmon.log
      - run: sudo fcli show fastnetmon_version
      - run: sudo CI=true ./installer -install_graphic_stack
  ubuntu2004_docker:
    machine:
      image: ubuntu-2004:current
    steps:
      - run: sudo apt-get update
      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: sudo CI=true ./installer -fastnetmon_docker
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - store_artifacts:
          path: /var/lib/fastnetmon_docker/fastnetmon/logs/fastnetmon.log
      - run: sudo fcli show fastnetmon_version
workflows:
  version: 2
  all_distros_nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
    jobs:
      - ubuntu2004
      - ubuntu2004_docker
  all_distros:
    jobs:
      - ubuntu2004
      - ubuntu2004_docker
