name: build-debian


on:
  workflow_call:
    inputs:
      docker_image:
        type: string
        required: true
      installer_arguments:
        type: string
        default: ""
      systemd_prepare_command:
        type: string
        default: "true"
      database_check_command:
        type: string
        default: "mongod --version"
      runner:
        type: string
        default: ubuntu-24.04
      installer_file_name:
        type: string
        default: installer
      mount_cgroup_command:
        type: string
        default: ""
      #machine_image:
      #  type: string
      #  default: "ubuntu-2204:current"
      visual_installer_command:
        type: string
        default: "./installer -install_graphic_stack -do_not_check_license"
      enable_ipv6:
        type: boolean
        default: false
      upgrade_from_community:
        type: boolean
        default: false

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
    - name: Show environment
      run: |
        uname -a
        uname -m
        docker version
        docker network inspect bridge
    - name: Enable IPv6
      if: ${{ inputs.enable_ipv6 }}
      run: |
        cat <<'EOF' | sudo tee /etc/docker/daemon.json
        {
          "ipv6": true,
          "fixed-cidr-v6": "2001:db8:1::/64",
          "ip6tables": true
        }
        EOF

        sudo systemctl restart docker

        docker network inspect bridge
    - name: Generate Dockerfile
      run: | 
        cat > Dockerfile <<EOF
        FROM ${{ inputs.docker_image }}
        ENV DEBIAN_FRONTEND=noninteractive
        RUN ${{ inputs.systemd_prepare_command }}
        RUN apt-get update; apt-get install -y systemd systemd-sysv
        CMD ["/lib/systemd/systemd"]
        EOF
    - name: Build image
      run: cat Dockerfile | sudo docker build --tag debian_systemd -

    - run: sudo apt-get update
    - run: sudo apt-get install -y net-tools
    - run: ifconfig
    - name: "Deploy new systemd enabled image"
      run: sudo docker run -d --privileged --cap-add SYS_ADMIN ${{ inputs.mount_cgroup_command }} --name linux_systemd_container debian_systemd /lib/systemd/systemd
    - run: sudo docker ps -a
    - run: sleep 10
    - name: Wait for container to start
      run: |
        sudo docker exec linux_systemd_container bash -lc '
        state="$(systemctl is-system-running --wait || true)"
        echo "Systemd state: $state"
        case "$state" in
          running|degraded)
            exit 0
            ;;
          # For older systemd (ubuntu 18/rhel 8)
          initializing|starting)
            sleep 3
            ;;
          *)
            exit 1
            ;;
        esac
        '
    - run: sudo docker exec linux_systemd_container systemctl status --no-pager
    - run: sudo docker exec linux_systemd_container apt install -y wget net-tools
    - run: sudo docker exec linux_systemd_container ifconfig
    - run: sudo docker exec linux_systemd_container wget --no-verbose "https://install.fastnetmon.com/${{ inputs.installer_file_name }}?random-argument-to-disable-caching-${{ github.run_id }}" -Oinstaller
    - run: sudo docker exec linux_systemd_container chmod +x installer
    - name: Install community 
      if: ${{ inputs.upgrade_from_community }}
      run: sudo docker exec --env "CI=true" linux_systemd_container ./installer -install_community_edition
    - name: Install community visual stack
      if: ${{ inputs.upgrade_from_community }}
      run: sudo docker exec --env "CI=true" linux_systemd_container ./installer -install_graphic_stack_community
    - run: sudo docker exec --env "CI=true" linux_systemd_container ./installer -do_not_check_license ${{ inputs.installer_arguments }}
    - run: sudo docker exec linux_systemd_container ldd /opt/fastnetmon/app/bin/fastnetmon 
    - name: Sleep to give enough time for FastNetMon to start
      run: sleep 25
    - run: sudo docker exec linux_systemd_container cat /var/log/fastnetmon/fastnetmon.log
    - run: sudo docker exec linux_systemd_container systemctl status fastnetmon
    - run: sudo docker exec linux_systemd_container ${{ inputs.database_check_command }}
    - run: sudo docker exec linux_systemd_container ldd /opt/fastnetmon/app/bin/traffic_db
    - run: sudo docker exec linux_systemd_container ldd /opt/fastnetmon/app/bin/fill_dictionaries
    - run: sudo docker exec linux_systemd_container /opt/fastnetmon/app/bin/fastnetmon --configuration_check --log_to_console
    - run: sudo docker exec linux_systemd_container fcli show fastnetmon_version
    - run: sudo docker exec linux_systemd_container fcli show main
    - run: sudo docker exec linux_systemd_container fcli show hostgroup
    - name: Check TCP listens for FastNetMon and database
      run: sudo docker exec linux_systemd_container netstat -lnpt
    - name: Check UDP listens for FastNetMon and database
      run: sudo docker exec linux_systemd_container netstat -lnpu
    - run: sudo docker exec --env "CI=true" linux_systemd_container ${{ inputs.visual_installer_command }}
    - name: Import community configuration
      if: ${{ inputs.upgrade_from_community }}
      run: sudo docker exec --env "CI=true" linux_systemd_container ./installer -import_community_edition_configuration
    - name: Check TCP listens for all daemons
      run: sudo docker exec linux_systemd_container netstat -lnpt
    - name: Check UDP listens for all daemons
      run: sudo docker exec linux_systemd_container netstat -lnpu
