name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 2 * * *" # UTC

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_debian:
    name: ${{ matrix.name }}
    uses: ./.github/workflows/build-debian.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu 24.04
            docker_image: ubuntu:24.04
          - name: Ubuntu 22.04 ARM FerretDB IPv6 developer
            docker_image: ubuntu:22.04
            installer_arguments: "-developer_version -ferretdb -ipv6_only_setup"
            visual_installer_command: "./installer -install_graphic_stack -do_not_check_license -ipv6_only_setup"
            installer_file_name: installer_arm64
            database_check_command: "/usr/bin/ferretdb --version"
            runner: ubuntu-24.04-arm
            enable_ipv6: true
          # Upgrade from community
          - name: Ubuntu 20.04 upgrade from community
            docker_image: ubuntu:20.04
            upgrade_from_community: true
    with:
      docker_image: ${{ matrix.docker_image }}
      installer_arguments:  ${{ matrix.installer_arguments || '' }}
      systemd_prepare_command: ${{ matrix.systemd_prepare_command || 'true' }}
      database_check_command: ${{ matrix.database_check_command || 'mongod --version'}}
      runner: ${{ matrix.runner || 'ubuntu-24.04' }}
      installer_file_name: ${{ matrix.installer_file_name || 'installer' }}
      mount_cgroup_command: ${{ matrix.mount_cgroup_command || ''}}
      visual_installer_command: ${{ matrix.visual_installer_command || './installer -install_graphic_stack -do_not_check_license'}}
      enable_ipv6: ${{ matrix.enable_ipv6 || false }}
      upgrade_from_community: ${{ matrix.upgrade_from_community || false }}

  #build_debian_from_community:
  #  name: ${{ matrix.name }}
  #  uses: ./.github/workflows/build-debian-upgrade-from-community.yml
  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      include:
  #        - name: Ubuntu 20.04 upgrade from community
  #          docker_image: ubuntu:20.04
  #  with:
  #    docker_image: ${{ matrix.docker_image }}
  #    systemd_prepare_command: ${{ matrix.systemd_prepare_command || 'true' }}
  #    runner: ${{ matrix.runner || 'ubuntu-24.04' }}

  build_rhel:
    name: ${{ matrix.name }}
    uses: ./.github/workflows/build-redhat.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: AlmaLinux 8
            docker_image: almalinux:8

          - name: AlmaLinux 8 upgrade from community
            docker_image: almalinux:8
            upgrade_from_community: true
    with:
      docker_image: ${{ matrix.docker_image }}
      installer_arguments:  ${{ matrix.installer_arguments || '' }}
      database_check_command: ${{ matrix.database_check_command || 'mongod --version'}}
      mount_cgroup_command: ${{ matrix.mount_cgroup_command || ''}}
      upgrade_from_community: ${{ matrix.upgrade_from_community || false }}
      runner: ${{ matrix.runner || 'ubuntu-24.04' }}
